# Generated by Django 6.0.1 on 2026-01-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0002_rename_user_id_chatmessage_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender_name',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='room_id',
            field=models.CharField(default='temp', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(default='temp', max_length=255),
            preserve_default=False,
        ),
    ]
